#fireBase:
#  collection: tripLiveTracking
#  dbBaseUrl: https://school-site-b5f25-default-rtdb.firebaseio.com/
#  authFileLocation: xxxxxxxxxxx.adminsdk.json
#  ideaTimeSpanInMinute: 5
#  liveTrackingIntervalInSecond: 2

#googleMap:
#  baseUrl: https://maps.googleapis.com/maps/api/distancematrix/json
#  apiKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#  mode: bus

#spring:
#  r2dbc:
#    username: ${DB_USER_NAME:dev_school_admin} #edit
#    password: ${DB_PASSWORD:4ea0b60ff37d4a139584309f8} #edit
#    url: ${DB URL:r2dbc:pool:postgresql://ulia-dev.smartsafeschool.com:5432/dev_school_db} #edit

#spring:
#  r2dbc:
#    host: ${DB_HOST:127.0.0.1}
#    port: 5432
#    database: dev_school_db
#    username: ${DB_USER_NAME:dev_school_admin} #edit
#    password: ${DB_PASSWORD:4ea0b60ff37d4a139584309f8} #edit
#    url: ${DB URL:r2dbc:pool:postgresql://ulia-dev.smartsafeschool.com:5432/dev_school_db} #edit
