name: Maven Package

on:
  release:
    types: [push]

jobs:
  build:

    runs-on: windows-latest #ubuntu
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 1.17
        distribution: 'adopt'
        #server-id: uliaKolosovich #github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn --batch-mode deploy #mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #ULIA_KOLOSOVICH }} #secrets.GITHUB_TOKEN }} #github.token }}
