name: "Create draft release"

on:
  push:
    branches:
      - gitHub_Actions

jobs:
  update_draft_release:
    runs-on: windows-latest # ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Все пулл-реквесты будут собираться в release notes